const PDFDocument = require('pdfkit');

/**
 * Service to generate professional resume PDFs
 */
class PDFService {
    /**
     * Generate a PDF from resume text
     * @param {string} resumeText - The rewritten resume content
     * @returns {Promise<Buffer>}
     */
    async generateResumePDF(resumeText) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                let buffers = [];

                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => {
                    let pdfData = Buffer.concat(buffers);
                    resolve(pdfData);
                });

                // Styling
                doc.fillColor('#000000')
                    .font('Helvetica-Bold')
                    .fontSize(24)
                    .text('REBUILT RESUME', { align: 'center' });

                doc.moveDown()
                    .fontSize(10)
                    .fillColor('#666666')
                    .text('Optimized for ATS & Recruiter Impact', { align: 'center' });

                doc.moveDown(2)
                    .strokeColor('#7c3aed')
                    .lineWidth(2)
                    .moveTo(50, doc.y)
                    .lineTo(550, doc.y)
                    .stroke();

                doc.moveDown(2)
                    .fillColor('#000000')
                    .font('Helvetica')
                    .fontSize(11)
                    .text(resumeText, {
                        align: 'left',
                        lineGap: 5
                    });

                doc.moveDown(5)
                    .fontSize(8)
                    .fillColor('#cccccc')
                    .text('Generated by Resume Rejection Analyzer - Show the world your true value.', { align: 'center' });

                doc.end();
            } catch (error) {
                console.error('❌ PDF Generation failed:', error);
                reject(error);
            }
        });
    }
}

module.exports = new PDFService();
